name: voice_message_package
description: Flutter package to play/puase voice message in chat messengers.
version: 2.1.4
homepage: https://mehran.monster/htmls/voicey.html

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.4.0
  syncfusion_flutter_sliders: ^24.1.41
  # ffmpeg_kit_flutter: ^6.0.3
  path_provider:
  http:
  # flutter_sound:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


